spring:
  application:
    name: MillionRecords
  datasource:
    username: postgres
    password: your_secure_password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/millionrecord
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: beans,health